language: objective-c
osx_image: xcode7.3

script:
- cd DocGenerator 
- xctool clean build -project DocGenerator.xcodeproj -scheme DocGenerator
- xctool test -project DocGenerator.xcodeproj -scheme DocGenerator
